services:
  mc:
    image: itzg/minecraft-server
    environment:
      # Core
      EULA: "true"
      USE_MEOWICE_FLAGS: "true"
      TZ: "America/Los_Angeles"
      MEMORY: "10000M"

      # Performance
      VIEW_DISTANCE: "16"
      SIMULATION_DISTANCE: "6"
      ENTITY_BROADCAST_RANGE_PERCENTAGE: "1000"

      # Server
      VERSION: "1.21.10"
      TYPE: "PAPER"
      ICON: /icon.png
      MOTD: "§8OBS§fIDIOTS§r IS BACK BABY ♪♩"
      OVERRIDE_ICON: true

      # World
      WORLD: /worlds/world
      FORCE_WORLD_COPY: false # THIS IS DANGEROUS, IT WILL DELETE THE WORLD. LEAVE AS FALSE.
      SEED: "5441383801202158949"
      DIFFICULTY: "3"
      SPAWN_PROTECTION: "0" # radius in blocks

      # Options
      ALLOW_FLIGHT: "true" # prevents players from being kicked when lagging
      LOG_IPS: "false"
      MAX_WORLD_SIZE: "1000000"
      ENFORCE_SECURE_PROFILE: "false"

      # Plugins
      PLUGINS: |-
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.5.1/PAPER/ViaVersion-5.5.1.jar
        https://cdn.modrinth.com/data/NpvuJQoq/versions/Ex8pP0Ax/ViaBackwards-5.5.1.jar
        https://github.com/plan-player-analytics/Plan/releases/download/5.6.2965/Plan-5.6-build-2965.jar
        https://get.discordsrv.com/
        https://cdn.modrinth.com/data/cUhi3iB2/versions/OW7YKtaI/tabtps-paper-1.3.29.jar
        https://cdn.modrinth.com/data/9eGKb6K1/versions/ps3C3lpD/voicechat-bukkit-2.6.6.jar
        https://hangarcdn.papermc.io/plugins/Gecolay/GSit/versions/3.0.1/PAPER/GSit-3.0.1.jar
        https://www.patreon.com/file?h=145853143&m=580728422
        https://cdn.modrinth.com/data/1u6JkXh5/versions/sO1YYZp4/worldedit-bukkit-7.4.0-beta-02.jar
      
      # Resources
      RESOURCE_PACK: "https://drive.google.com/uc?export=download&id=1EQXjnDoi9TIX84DwyCeTWy0kJlDXl17M"
      RESOURCE_PACK_REQUIRED: "true"

      # Welcome messages
      RCON_CMDS_FIRST_CONNECT: |-
        /tellraw @a ["",{"text":"Hai ","color":"white"},{"selector":"@a","bold":true,"color":"#b00b50"},{"text":"! Thank you so much for joining!","color":"white"}]

      # Admin
      OPS: |-
        SillyLucy_
      ENABLE_WHITELIST: "false" # whitelist is not needed rn
    ports:
      - "22000:25565"         # Minecraft
      - "22001:22001/udp"     # Voice Chat
      - "22002:8804/tcp"      # Plan Web server
    volumes:
      - data:/data
      - ./data:/data
      - ./world:/worlds/world
      - ./icon.png:/icon.png
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}










